version: '2'
services:
  actioncatalogservicesql-app:
    image: actioncatalogservicesql
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://actioncatalogservicesql-postgresql:5432/ActionCatalogServiceSQL
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  actioncatalogservicesql-postgresql:
    extends:
      file: postgresql.yml
      service: actioncatalogservicesql-postgresql
